spring.application.name=rsvp-backend
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}


firebase.serviceAccount=${FIREBASE_SERVICE_ACCOUNT}
firebase.projectId=${FIREBASE_PROJECT_ID}


# ===============================
# Brevo SMTP configuration
# ===============================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_LOGIN}
spring.mail.password=${BREVO_SMTP_KEY}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${MAIL_FROM}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

