spring.application.name=rsvp-backend
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}


firebase.serviceAccount=${FIREBASE_SERVICE_ACCOUNT}
firebase.projectId=${FIREBASE_PROJECT_ID}

# ===============================
# Mailgun configuration (HTTP API)
# ===============================
mailgun.apiKey=${MAILGUN_API_KEY}
mailgun.domain=${MAILGUN_DOMAIN}
mailgun.baseUrl=${MAILGUN_BASE_URL:https://api.mailgun.net}
app.mail.from=${MAIL_FROM}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
