spring.application.name=rsvp-backend
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}


firebase.serviceAccount=classpath:firebase-key.json
firebase.projectId=rsvp-website-94fbb

# ===============================
# Gmail SMTP configuration
# ===============================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# App mail settings
# ===============================
app.mail.from=${MAIL_USERNAME}

